services:
  datalab:
    build:
      context: .
      dockerfile: Tooling/prod/Dockerfile
    image: docr/datalab
    command: daphne -b 0.0.0.0 -p 8000 datalab.asgi:application
    # command: gunicorn --workers=4 datalab.wsgi:application --bind 0.0.0.0:8000  --timeout 600
    volumes:
      - datalab_media:/app/media
      - datalab_static:/app/static
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - datalab
    depends_on:
      - db
      - influx
      - caddy
      - redis

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - datalab
    env_file:
      - .env.prod

  influx:
    image: influxdb:2
    restart: unless-stopped
    networks:
      - datalab
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    networks:
      - datalab

  caddy:
    image: caddy:latest
    ports:
      - "8040:80"
    volumes:
      - datalab_media:/srv/media
      - datalab_static:/srv/static
      - ./Tooling/prod/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - datalab
    restart: unless-stopped

volumes:
  db:
  datalab_media:
  datalab_static:
  influxdb_data:
  influxdb_config:

networks:
  datalab: