services:
  sensebox:
    build:
      context: .
      dockerfile: Tooling/dev/Dockerfile
    image: sensebox
    command: gunicorn --workers=1 sensebox.wsgi:application --bind 0.0.0.0:8000  --timeout 600
    #./manage.py runserver 0.0.0.0:8000 # --settings=sensebox.settings.dev
    #command: uvicorn sensebox.wsgi:application --settings=sensebox.settings.dev --reload --workers=8
    #command: daphne -b 0.0.0.0 -p 8000 sensebox.asgi:application
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=sensebox.settings.dev
    env_file:
      - .env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    # restart: always
    volumes:
      - sensebox.dev.db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env/.env.dev

volumes:
  sensebox.dev.db: