# Generated by Django 5.1.1 on 2024-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statisticsbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigator',
        ),
        migrations.DeleteModel(
            name='StatisticsBase',
        ),
    ]
