# Generated by Django 5.1.4 on 2025-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_navigator_delete_statisticsbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Der Name, der im Menu gezeigt werden soll.', max_length=255)),
                ('html_id', models.CharField(help_text='ein eindeutiger Bezeichner, keine Dopplungen, keine Leerzeichen', max_length=255)),
            ],
        ),
    ]
