# Generated by Django 5.1.6 on 2025-02-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigator',
        ),
    ]
