# Generated by Django 5.0.6 on 2024-06-03 11:24

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHome',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('blog_cards', wagtail.blocks.StructBlock([]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('title_image', wagtail.images.blocks.ImageChooserBlock(help_text='Titelbild des Blogeintrags', required=True)), ('title_text', wagtail.blocks.CharBlock(help_text='Titel des Blogeintrags', required=True)), ('content', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(null=True)), ('text', wagtail.blocks.CharBlock(default='Button Text', null=True))])))], help_text='Inhalt des Blogeintrags'))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
