# Generated by Django 5.0.6 on 2024-06-04 10:40

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', wagtail.blocks.StructBlock([('title_image', wagtail.images.blocks.ImageChooserBlock(help_text='Titelbild des Blogeintrags', required=True)), ('title_text', wagtail.blocks.CharBlock(help_text='Titel des Blogeintrags', required=True)), ('content', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(null=True)), ('text', wagtail.blocks.CharBlock(default='Button Text', null=True))]))), ('image_with_text', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(null=True)), ('text', wagtail.blocks.CharBlock(null=True))])))], help_text='Inhalt des Blogeintrags'))]))]),
        ),
    ]
