# Generated by Django 5.0.6 on 2024-05-30 15:20

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('tag', wagtail.blocks.CharBlock(default='', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'lead', 'hr', 'ul', 'ol', 'bold', 'italic'], help_text='Textfeld für beliebigen Text'))])), ('buttons', wagtail.blocks.StructBlock([('button_paartherapie', wagtail.blocks.CharBlock(default='Paartherapie')), ('tag_paartherapie', wagtail.blocks.CharBlock(default='paartherapie', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_psychologische_psychotherapie', wagtail.blocks.CharBlock(default='Psychologische Psychotherapie')), ('tag_psychologische_psychotherapie', wagtail.blocks.CharBlock(default='psychologische_psychotherapie', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_trennungsberatung', wagtail.blocks.CharBlock(default='Trennungsberatung')), ('tag_trennungsberatung', wagtail.blocks.CharBlock(default='trennungsberatung', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_psychologische_beratung', wagtail.blocks.CharBlock(default='Psychologische Beratung')), ('tag_psychologische_beratung', wagtail.blocks.CharBlock(default='psychologische_beratung', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.'))])), ('contact', wagtail.blocks.StructBlock([('name_text', wagtail.blocks.CharBlock(default='Name')), ('name_placeholder', wagtail.blocks.CharBlock(default='Name')), ('email_text', wagtail.blocks.CharBlock(default='E-Mail')), ('email_placeholder', wagtail.blocks.CharBlock(default='hello@mail.de')), ('message_text', wagtail.blocks.CharBlock(default='Nachricht')), ('message_placeholder', wagtail.blocks.CharBlock(default='Schreiben Sie mir!')), ('send_button', wagtail.blocks.CharBlock(default='Nachricht senden')), ('thank_you_text', wagtail.blocks.CharBlock(default='Die Nachricht wurde gesendet.'))])), ('round_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Rundes Bild (800 x 800 px)', null=True)), ('subtitle_text', wagtail.blocks.CharBlock(default='Untertitel'))]))], default=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('header8', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 1', null=True)), ('image2', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 2', null=True)), ('image3', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 3', null=True)), ('text1', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.')), ('text2', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.')), ('text3', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.'))]))], null=True),
        ),
    ]
