# Generated by Django 5.0.6 on 2024-05-30 15:55

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 1', null=True)), ('image2', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 2', null=True)), ('image3', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Hero Image 3', null=True)), ('text1', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.')), ('text2', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.')), ('text3', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'lead'], help_text='Er besteht aus einer Überschrift und einem Textblock darunter. Der obere Text ist mit H1 und der darunter mit H3 formatiert.'))]))], null=True),
        ),
    ]
