# Generated by Django 5.0.6 on 2024-05-30 18:27

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('heros', wagtail.blocks.StructBlock([('hero_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Bild', null=True)), ('text', wagtail.blocks.RichTextBlock(default='Etwas Text, der in H1 über dem Bild angezeigt wird.'))])))]))], null=True),
        ),
    ]
