# Generated by Django 5.0.6 on 2024-05-30 18:52

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('tag', wagtail.blocks.CharBlock(default='', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'lead', 'hr', 'ul', 'ol', 'bold', 'italic'], help_text='Textfeld für beliebigen Text'))])), ('buttons', wagtail.blocks.StructBlock([('button_paartherapie', wagtail.blocks.CharBlock(default='Paartherapie')), ('tag_paartherapie', wagtail.blocks.CharBlock(default='paartherapie', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_psychologische_psychotherapie', wagtail.blocks.CharBlock(default='Psychologische Psychotherapie')), ('tag_psychologische_psychotherapie', wagtail.blocks.CharBlock(default='psychologische_psychotherapie', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_trennungsberatung', wagtail.blocks.CharBlock(default='Trennungsberatung')), ('tag_trennungsberatung', wagtail.blocks.CharBlock(default='trennungsberatung', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.')), ('button_psychologische_beratung', wagtail.blocks.CharBlock(default='Psychologische Beratung')), ('tag_psychologische_beratung', wagtail.blocks.CharBlock(default='psychologische_beratung', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/ oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.'))])), ('contact', wagtail.blocks.StructBlock([('name_text', wagtail.blocks.CharBlock(default='Name')), ('name_placeholder', wagtail.blocks.CharBlock(default='Name')), ('email_text', wagtail.blocks.CharBlock(default='E-Mail')), ('email_placeholder', wagtail.blocks.CharBlock(default='hello@mail.de')), ('message_text', wagtail.blocks.CharBlock(default='Nachricht')), ('message_placeholder', wagtail.blocks.CharBlock(default='Schreiben Sie mir!')), ('send_button', wagtail.blocks.CharBlock(default='Nachricht senden')), ('thank_you_text', wagtail.blocks.CharBlock(default='Die Nachricht wurde gesendet.'))])), ('big_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Großes Bild, geeignet für den Beginn eines Blogeintrags', null=True))]))], default=None),
        ),
    ]
