# Generated by Django 5.0.6 on 2024-06-01 11:28

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_body'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('blog_entry', wagtail.blocks.StructBlock([('title_text', wagtail.blocks.CharBlock(help_text='Titel des Blogeintrags', required=True)), ('title_image', wagtail.images.blocks.ImageChooserBlock(help_text='Titelbild des Blogeintrags', required=True)), ('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], help_text='Inhalt des Blogeintrags'))])), ('paragraph', wagtail.blocks.StructBlock([('tag', wagtail.blocks.CharBlock(default='', help='Ein "tag" ist ein Element bestehend auf Buchstaben und/oder Zahlen. Es ist meist kurz, einzigartig und enthält keine Leerzeichen. Zwei Elemente können verbunden werden, wenn sie den gleichen Tag haben.', required=False)), ('paragraph', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'lead', 'hr', 'ul', 'ol', 'bold', 'italic'], help_text='Textfeld für beliebigen Text'))])), ('big_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Großes Bild, geeignet für den Beginn eines Blogeintrags', null=True))]))], default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
