# Generated by Django 5.0.6 on 2024-06-01 16:57

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_body_alter_impressumpage_body'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('bricks', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(default='Überschrift', help_text='Überschrift mit Biene', null=True, required=True)), ('brick_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('double', wagtail.blocks.BooleanBlock(help_text='Das Bild in doppelter Breite anzeigen?', null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Bild', null=True)), ('text', wagtail.blocks.RichTextBlock(default='Etwas Text'))])))]))], default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
