# Generated by Django 5.0.6 on 2024-06-07 16:25

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homepage_body_alter_impressumpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('blog_entry', wagtail.blocks.StructBlock([('title_image', wagtail.images.blocks.ImageChooserBlock(help_text='Titelbild des Blogeintrags', required=True)), ('title_text', wagtail.blocks.CharBlock(help_text='Titel des Blogeintrags', required=True)), ('content', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link', wagtail.blocks.PageChooserBlock(null=True)), ('text', wagtail.blocks.CharBlock(default='Button Text', null=True))]))), ('image_with_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(null=True)), ('text', wagtail.blocks.CharBlock(null=True))]))], help_text='Inhalt des Blogeintrags'))])), ('paragraph', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(help_text='Textfeld für beliebigen Text'))])), ('big_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Großes Bild, geeignet für den Beginn eines Blogeintrags', null=True))])), ('bricks', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(default='Überschrift', help_text='Überschrift mit Biene', null=True, required=True)), ('brick_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('double', wagtail.blocks.BooleanBlock(help_text='Das Bild in doppelter Breite anzeigen?', null=True, required=False)), ('cubic', wagtail.blocks.BooleanBlock(help_text='Das Bild in groß als Quadrat anzeigen?', null=True, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Bild', null=True)), ('text', wagtail.blocks.RichTextBlock(null=True, required=False))])))]))], default=None),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('heros', wagtail.blocks.StructBlock([('hero_list', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Bild', null=True)), ('text', wagtail.blocks.RichTextBlock(default='Etwas Text, der in H1 über dem Bild angezeigt wird.'))])))]))], null=True),
        ),
        migrations.AlterField(
            model_name='impressumpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('paragraph', wagtail.blocks.RichTextBlock(help_text='Textfeld für beliebigen Text'))]))], default=None),
        ),
    ]
