# Generated by Django 5.1.1 on 2024-09-12 12:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_impressumpage_page_ptr_remove_homepage_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('statistics_placeholder', 0), ('paragraph', 2)], block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed'], 'help_text': 'Textfeld für beliebigen Text'}), 2: ('wagtail.blocks.StructBlock', [[('paragraph', 1)]], {})}, default=None),
        ),
    ]
