# Generated by Django 5.1.1 on 2024-09-12 14:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('statistics_placeholder', 0), ('paragraph', 2)], blank=True, block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed'], 'help_text': 'Textfeld für beliebigen Text', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('paragraph', 1)]], {})}, default=None, null=True),
        ),
    ]
