# Generated by Django 5.1.1 on 2024-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseBoxTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensebox_id', models.CharField(help_text='ID der SenseBox', max_length=255)),
                ('name', models.CharField(blank=True, help_text='(optional) Name der SenseBox', max_length=255)),
                ('location', models.CharField(blank=True, help_text='(optional) Standort im Format: 52.516221, 13.3992', max_length=255)),
                ('textfield', models.TextField(help_text='(optional) Textfeld für Notizen')),
            ],
        ),
    ]
