# Generated by Django 5.1.1 on 2024-09-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_senseboxtable_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senseboxtable',
            options={'verbose_name': 'SenseBox', 'verbose_name_plural': 'SenseBox Table'},
        ),
    ]
