# Generated by Django 5.1.1 on 2024-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_senseboxtable_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseboxtable',
            name='textfield',
            field=models.TextField(blank=True, help_text='(optional) Textfeld für Notizen'),
        ),
    ]
