# Generated by Django 5.1.1 on 2024-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_senseboxtable_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senseboxtable',
            name='location',
        ),
        migrations.AddField(
            model_name='senseboxtable',
            name='location_latitude',
            field=models.FloatField(blank=True, help_text='(optional) Latitude der SenseBox. Wird nach einigen Minuten automatisch ausgefüllt. Format 52...', null=True),
        ),
        migrations.AddField(
            model_name='senseboxtable',
            name='location_longitude',
            field=models.FloatField(blank=True, help_text='(optional) Longitude der SenseBox. Wird nach einigen Minuten automatisch ausgefüllt. Format 13...', null=True),
        ),
    ]
