# Generated by Django 5.1.1 on 2024-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_senseboxtable_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseboxtable',
            name='location_latitude',
            field=models.CharField(blank=True, help_text='(optional) Latitude der SenseBox. Wird nach einigen Minuten automatisch ausgefüllt. Format 52...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senseboxtable',
            name='location_longitude',
            field=models.CharField(blank=True, help_text='(optional) Longitude der SenseBox. Wird nach einigen Minuten automatisch ausgefüllt. Format 13...', max_length=255, null=True),
        ),
    ]
