# Generated by Django 5.1.1 on 2024-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_senseboxtable_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senseboxtable',
            name='error_message',
            field=models.CharField(blank=True, help_text='Fehlermeldung der Box. Möglicherweise offline, fehlerhafte Werte etc. Box dann entfernen.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senseboxtable',
            name='location_latitude',
            field=models.CharField(blank=True, help_text='(optional) Latitude der SenseBox. Wird automatisch ermittelt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senseboxtable',
            name='location_longitude',
            field=models.CharField(blank=True, help_text='(optional) Longitude der SenseBox. Wird automatisch ermittelt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senseboxtable',
            name='name',
            field=models.CharField(blank=True, help_text='(optional) Name der SenseBox. Wird automatisch ermittelt', max_length=255),
        ),
    ]
