# Generated by Django 5.1.2 on 2024-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_senseboxtable_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='ID des Sensors', max_length=255)),
                ('name', models.CharField(blank=True, help_text='(optional) Name des Sensors', max_length=255)),
                ('lat', models.CharField(blank=True, help_text='(optional) Latitude des Sensors', max_length=255)),
                ('lon', models.CharField(blank=True, help_text='(optional) Longitude des Sensors', max_length=255)),
            ],
            options={
                'verbose_name': 'Sensors Info',
                'verbose_name_plural': 'Sensors Info Table',
            },
        ),
    ]
