# Generated by Django 5.1.2 on 2024-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_sensorsinfotable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lat',
            field=models.CharField(blank=True, editable=False, help_text='Latitude des Sensors', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lon',
            field=models.CharField(blank=True, editable=False, help_text='Longitude des Sensors', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='name',
            field=models.CharField(blank=True, editable=False, help_text='Name des Sensors', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_id',
            field=models.CharField(editable=False, help_text='ID des Sensors', max_length=255),
        ),
    ]
