# Generated by Django 5.1.2 on 2024-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_sensorsinfotable_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsinfotable',
            name='box_id',
            field=models.CharField(blank=True, editable=False, help_text='ID der Box', max_length=255),
        ),
    ]
