# Generated by Django 5.1.2 on 2024-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_sensorsinfotable_box_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsinfotable',
            name='box_grouptag',
            field=models.CharField(blank=True, editable=False, help_text='Box Grouptag', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='box_id',
            field=models.CharField(blank=True, editable=False, help_text='Box ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lat',
            field=models.CharField(blank=True, editable=False, help_text='Latitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lon',
            field=models.CharField(blank=True, editable=False, help_text='Longitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_id',
            field=models.CharField(editable=False, help_text='Sensor ID', max_length=255),
        ),
    ]
