# Generated by Django 5.1.3 on 2024-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_name_sensorsinfotable_box_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='box_id',
        ),
        migrations.AddField(
            model_name='sensorsinfotable',
            name='senor_unit',
            field=models.CharField(default='', editable=False, help_text='Sensor Unit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsinfotable',
            name='sensor_name',
            field=models.CharField(default='', editable=False, help_text='Sensor Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorsinfotable',
            name='sensor_type',
            field=models.CharField(default='', editable=False, help_text='Sensor Type', max_length=255),
            preserve_default=False,
        ),
    ]
