# Generated by Django 5.1.3 on 2024-11-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_sensorsinfotable_box_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsinfotable',
            old_name='senor_unit',
            new_name='sensor_unit',
        ),
    ]
