# Generated by Django 5.1.3 on 2024-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_rename_senor_unit_sensorsinfotable_sensor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='box_grouptag',
            field=models.CharField(blank=True, help_text='Box Grouptag', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='box_name',
            field=models.CharField(blank=True, help_text='Name des Sensors', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lat',
            field=models.CharField(blank=True, help_text='Latitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='lon',
            field=models.CharField(blank=True, help_text='Longitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_id',
            field=models.CharField(help_text='Sensor ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_name',
            field=models.CharField(help_text='Sensor Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_type',
            field=models.CharField(help_text='Sensor Type', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensorsinfotable',
            name='sensor_unit',
            field=models.CharField(help_text='Sensor Unit', max_length=255),
        ),
    ]
