# Generated by Django 5.1.3 on 2024-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_sensorsinfotable_box_grouptag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseBoxLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.CharField(default='', help_text='Latitude: Zentraler Punkt eines Ortes/ einer Stadt für den im Umkreis automatisch SenseBoxen ermittelt werden sollen.', max_length=255)),
                ('location_longitude', models.CharField(help_text='Longitude: Zentraler Punkt eines Ortes/ einer Stadt für den im Umkreis automatisch SenseBoxen ermittelt werden sollen.', max_length=255)),
                ('maxDistance', models.IntegerField(default='30000', help_text='Radius um den Mittelpunkt, der einbezogen werden soll.')),
                ('exposure', models.CharField(default='outdoor', help_text='Welche Art von Sensor soll dargestellt werden? Erlaubte Werte: "indoor", "outdoor", "mobile", "unknown"', max_length=50)),
            ],
            options={
                'verbose_name': 'SenseBox Location',
                'verbose_name_plural': 'SenseBox Locations',
            },
        ),
    ]
