# Generated by Django 5.1.3 on 2024-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_senseboxlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='senseboxlocation',
            name='name',
            field=models.CharField(blank=True, default='leer', help_text='(optional) Name des Ortes', max_length=255),
        ),
        migrations.AlterField(
            model_name='senseboxlocation',
            name='location_latitude',
            field=models.CharField(default='52.516221', help_text='Latitude: Zentraler Punkt eines Ortes/ einer Stadt für den im Umkreis automatisch SenseBoxen ermittelt werden sollen.', max_length=255),
        ),
        migrations.AlterField(
            model_name='senseboxlocation',
            name='location_longitude',
            field=models.CharField(default='13.3992', help_text='Longitude: Zentraler Punkt eines Ortes/ einer Stadt für den im Umkreis automatisch SenseBoxen ermittelt werden sollen.', max_length=255),
        ),
        migrations.AlterField(
            model_name='senseboxlocation',
            name='maxDistance',
            field=models.IntegerField(default='30000', help_text='Radius um den Mittelpunkt, der einbezogen werden soll in Metern.'),
        ),
    ]
