# Generated by Django 5.1.3 on 2024-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_senseboxlocation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='senseboxtable',
            name='grouptags',
            field=models.ManyToManyField(blank=True, to='home.grouptag', verbose_name='associated Group Tags'),
        ),
    ]
