# Generated by Django 5.1.3 on 2024-11-14 12:16

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_grouptag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptag',
            name='tag',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='grouptag',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tag',), name='unique_tag_constraint'),
        ),
    ]
