# Generated by Django 5.1.4 on 2025-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_grouptag_tag_grouptag_unique_tag_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='gif_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
