# Generated by Django 5.1.4 on 2025-01-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_homepage_gif_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='gif_image',
        ),
    ]
