# Generated by Django 5.1.4 on 2025-01-09 13:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_remove_homepage_gif_image'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('bricks', 7), ('iNaturalist', 8)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Überschrift', 'help_text': 'Überschrift mit Biene', 'null': True, 'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Das Bild in doppelter Breite anzeigen?', 'null': True, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Das Bild in groß als Quadrat anzeigen?', 'null': True, 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'help_text': 'Bild', 'null': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('double', 1), ('cubic', 2), ('image', 3), ('text', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('header', 0), ('brick_list', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[]], {})}, default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImpressumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed'], 'help_text': 'Textfeld für beliebigen Text'}), 1: ('wagtail.blocks.StructBlock', [[('paragraph', 0)]], {})}, default=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='senseboxtable',
            name='grouptags',
        ),
        migrations.DeleteModel(
            name='SenseBoxLocation',
        ),
        migrations.DeleteModel(
            name='SensorsInfoTable',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.StreamField([('heros', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'help_text': 'Bild', 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'default': 'Etwas Text, der in H1 über dem Bild angezeigt wird.'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('hero_list', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('blog_entry', 12), ('paragraph', 14), ('big_image', 16), ('bricks', 24)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Titelbild des Blogeintrags', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titel des Blogeintrags', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.PageChooserBlock', (), {'null': True}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Button Text', 'null': True}), 6: ('wagtail.blocks.StructBlock', [[('link', 4), ('text', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'null': True}), 9: ('wagtail.blocks.CharBlock', (), {'null': True}), 10: ('wagtail.blocks.StructBlock', [[('image', 8), ('text', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('image', 2), ('paragraph', 3), ('button', 7), ('image_with_text', 10)]], {'help_text': 'Inhalt des Blogeintrags'}), 12: ('wagtail.blocks.StructBlock', [[('title_image', 0), ('title_text', 1), ('content', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'image', 'embed'], 'help_text': 'Textfeld für beliebigen Text'}), 14: ('wagtail.blocks.StructBlock', [[('paragraph', 13)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'help_text': 'Großes Bild, geeignet für den Beginn eines Blogeintrags', 'null': True}), 16: ('wagtail.blocks.StructBlock', [[('image', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Überschrift', 'help_text': 'Überschrift mit Biene', 'null': True, 'required': True}), 18: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Das Bild in doppelter Breite anzeigen?', 'null': True, 'required': False}), 19: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Das Bild in groß als Quadrat anzeigen?', 'null': True, 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'help_text': 'Bild', 'null': True}), 21: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('double', 18), ('cubic', 19), ('image', 20), ('text', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('header', 17), ('brick_list', 23)]], {})}, default=None),
        ),
        migrations.DeleteModel(
            name='GroupTag',
        ),
        migrations.DeleteModel(
            name='SenseBoxTable',
        ),
    ]
