# Generated by Django 5.1.6 on 2025-02-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_grouptag_id_alter_senseboxlocation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorsinfotable',
            old_name='sensor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sensorsinfotable',
            old_name='sensor_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='box_grouptag',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='box_name',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='sensorsinfotable',
            name='sensor_type',
        ),
    ]
